package store

import (
	"cmp"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"slices"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/rossbrandon/minimovie-api/internal/metrics"
)

const movieColumns = `id, source_id, slug, title, original_title, overview, release_date, runtime_minutes, popularity,
	vote_average, poster_path, genres, collection_id, payload, stale, fetched_at, created_at, updated_at`

type Movie struct {
	ID             int             `db:"id"`
	SourceID       int             `db:"source_id"`
	Slug           string          `db:"slug"` // generated by the database from id and title
	Title          string          `db:"title"`
	OriginalTitle  *string         `db:"original_title"`
	Overview       *string         `db:"overview"`
	ReleaseDate    *time.Time      `db:"release_date"`
	RuntimeMinutes *int            `db:"runtime_minutes"`
	Popularity     float64         `db:"popularity"`
	VoteAverage    *float64        `db:"vote_average"`
	PosterPath     *string         `db:"poster_path"`
	Genres         []string        `db:"genres"`
	CollectionID   *int            `db:"collection_id"` // collections.id
	Payload        json.RawMessage `db:"payload"`       // nil = not hydrated
	Stale          bool            `db:"stale"`
	FetchedAt      *time.Time      `db:"fetched_at"`
	CreatedAt      time.Time       `db:"created_at"`
	UpdatedAt      time.Time       `db:"updated_at"`
}

type MovieStore struct {
	catalogTable
}

type skeletonArrays struct {
	sourceIDs  []int32
	titles     []string
	overviews  []*string
	posters    []*string
	dates      []*string
	votes      []*float32
	popularity []float32
}

func NewMovieStore(pool *pgxpool.Pool) *MovieStore {
	return &MovieStore{catalogTable{pool: pool, name: "movies"}}
}

func (s *MovieStore) GetByID(ctx context.Context, id int) (*Movie, error) {
	return s.getOne(ctx, `where id = $1`, id)
}

func (s *MovieStore) GetBySourceID(ctx context.Context, sourceID int) (*Movie, error) {
	return s.getOne(ctx, `where source_id = $1`, sourceID)
}

func (s *MovieStore) UpsertHydrated(ctx context.Context, db DBTX, m Movie) (int, error) {
	defer metrics.TrackDbDuration(ctx, "write")()
	if m.Genres == nil {
		m.Genres = []string{}
	}

	id, err := scanID(db.QueryRow(ctx, `
		insert into movies (source_id, title, original_title, overview, release_date, runtime_minutes, popularity,
		                    vote_average, poster_path, genres, collection_id, payload, stale, fetched_at, updated_at)
		values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, false, now(), now())
		on conflict (source_id) do update set
			title           = excluded.title,
			original_title  = excluded.original_title,
			overview        = excluded.overview,
			release_date    = excluded.release_date,
			runtime_minutes = excluded.runtime_minutes,
			popularity      = excluded.popularity,
			vote_average    = excluded.vote_average,
			poster_path     = excluded.poster_path,
			genres          = excluded.genres,
			collection_id   = excluded.collection_id,
			payload         = excluded.payload,
			stale           = false,
			fetched_at      = now(),
			updated_at      = now()
		returning id`,
		m.SourceID, m.Title, m.OriginalTitle, m.Overview, nullTime(m.ReleaseDate), m.RuntimeMinutes, m.Popularity,
		m.VoteAverage, m.PosterPath, m.Genres, m.CollectionID, m.Payload))
	if err != nil {
		return 0, fmt.Errorf("movie store: upsert source %d: %w", m.SourceID, err)
	}
	return id, nil
}

func (s *MovieStore) UpsertSkeleton(ctx context.Context, db DBTX, rows []Skeleton) error {
	if len(rows) == 0 {
		return nil
	}
	defer metrics.TrackDbDuration(ctx, "write")()

	cols := skeletonColumns(rows)
	_, err := db.Exec(ctx, `
		insert into movies (source_id, title, original_title, overview, poster_path, release_date, vote_average, popularity, updated_at)
		select u.source_id, u.title, u.title, u.overview, u.poster, u.release_date::date, u.vote, u.popularity, now()
		from unnest($1::int[], $2::text[], $3::text[], $4::text[], $5::text[], $6::real[], $7::real[])
			as u(source_id, title, overview, poster, release_date, vote, popularity)
		on conflict (source_id) do update set
			popularity   = case when movies.payload is null and excluded.popularity > 0
			               then excluded.popularity else movies.popularity end,
			title        = case when movies.payload is null then excluded.title else movies.title end,
			overview     = case when movies.payload is null then coalesce(excluded.overview, movies.overview) else movies.overview end,
			poster_path  = case when movies.payload is null then coalesce(excluded.poster_path, movies.poster_path) else movies.poster_path end,
			release_date = case when movies.payload is null then coalesce(excluded.release_date, movies.release_date) else movies.release_date end,
			vote_average = case when movies.payload is null then coalesce(excluded.vote_average, movies.vote_average) else movies.vote_average end,
			updated_at   = now()`,
		cols.sourceIDs, cols.titles, cols.overviews, cols.posters, cols.dates, cols.votes, cols.popularity)
	if err != nil {
		return fmt.Errorf("movie store: upsert skeletons: %w", err)
	}
	return nil
}

func (s *MovieStore) getOne(ctx context.Context, where string, arg any) (*Movie, error) {
	defer metrics.TrackDbDuration(ctx, "read")()

	rows, err := s.pool.Query(ctx, `select `+movieColumns+` from movies `+where, arg)
	if err != nil {
		return nil, fmt.Errorf("movie store: get: %w", err)
	}
	m, err := pgx.CollectOneRow(rows, pgx.RowToAddrOfStructByName[Movie])
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("movie store: get: %w", err)
	}
	return m, nil
}

func skeletonColumns(rows []Skeleton) skeletonArrays {
	slices.SortFunc(rows, func(a, b Skeleton) int { return cmp.Compare(a.SourceID, b.SourceID) })
	a := skeletonArrays{
		sourceIDs:  make([]int32, len(rows)),
		titles:     make([]string, len(rows)),
		overviews:  make([]*string, len(rows)),
		posters:    make([]*string, len(rows)),
		dates:      make([]*string, len(rows)),
		votes:      make([]*float32, len(rows)),
		popularity: make([]float32, len(rows)),
	}
	for i, r := range rows {
		a.sourceIDs[i] = int32(r.SourceID)
		a.titles[i] = r.Title
		a.overviews[i] = r.Overview
		a.posters[i] = r.PosterPath
		a.dates[i] = emptyToNil(r.ReleaseDate)
		a.popularity[i] = float32(r.Popularity)
		if r.VoteAverage != nil {
			v := float32(*r.VoteAverage)
			a.votes[i] = &v
		}
	}
	return a
}

func emptyToNil(s *string) *string {
	if s == nil || *s == "" {
		return nil
	}
	return s
}
