services:
  postgres:
    image: postgres:16-alpine
    container_name: minimovie-postgres
    environment:
      POSTGRES_USER: mmdb_user
      POSTGRES_PASSWORD: mmdb_password
      POSTGRES_DB: minimovie
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    shm_size: 256m

volumes:
  postgres_data:
